questions =  [
    {"id": 0, "question": "The government should reduce business regulations.", "effects": {"right": 1}},
    {"id": 1, "question": "Charity is a better way of helping those in need than social welfare.", "effects": {"right": 1}},
    {"id": 2, "question": "Wages are always fair, as employers know best what a worker's labour is worth.", "effects": {"right": 1}},
    {"id": 3, "question": "It is \"human nature\" to be greedy.", "effects": {"right": 1}},
    {"id": 4, "question": "\"Exploitation\" is an outdated term, as the struggles of 1800s capitalism don't exist anymore.", "effects": {"right": 1}},
    {"id": 5, "question": "Communism is an ideal that can never work in practice.", "effects": {"right": 1}},
    {"id": 6, "question": "Taxation of the wealthy is a bad idea, society would be better off without it.", "effects": {"right": 1}},
    {"id": 7, "question": "The harder you work, the more you progress up the social ladder.", "effects": {"right": 1}},
    {"id": 8, "question": "Organisations and corporations cannot be trusted and need to be regulated by the government.", "effects": {"right": -1}},
    {"id": 9, "question": "A universal basic income administered by the government is a good idea.", "effects": {"right": -1}},
    {"id": 10, "question": "The current welfare system  should be expanded by the government to further combat inequality.", "effects": {"right": -1}},
    {"id": 11, "question": "The government should nationalize or redistribute land.", "effects": {"right": -1}},
    {"id": 12, "question": "All industry and the bank should be nationalised.", "effects": {"right": -1}},
    {"id": 13, "question": "Sometimes it is right that the government may spy on its citizens to combat extremists and terrorists.", "effects": {"auth": 1}},
    {"id": 14, "question": "Authority figures, if morally correct, are a good thing for society.", "effects": {"auth": 1}},
    {"id": 15, "question": "Strength is necessary for any government to succeed.", "effects": {"auth": 1}},
    {"id": 16, "question": "Only the government can fairly and effectively regulate organisations.", "effects": {"auth": 1}},
    {"id": 17, "question": "Society requires structure and bureaucracy in order to function.", "effects": {"auth": 1}},
    {"id": 18, "question": "Mandatory IDs should be used to ensure public safety.", "effects": {"auth": 1}},
    {"id": 19, "question": "In times of crisis, safety becomes more important than civil liberties.", "effects": {"auth": 1}},
    {"id": 20, "question": "If you have nothing to hide, you have nothing to fear.", "effects": {"auth": 1}},
    {"id": 21, "question": "The government should be less involved in the day to day life of its citizens.", "effects": {"auth": -1}},
    {"id": 22, "question": "Monarchical governments are better than democratic governments.", "effects": {"auth": -1}},
    {"id": 23, "question": "Jury nullification should be legal.", "effects": {"auth": -1}},
    {"id": 24, "question": "The smaller the government, the freer the people.", "effects": {"auth": -1}},
    {"id": 25, "question": "The government should, at most, provide emergency services and law enforcement.", "effects": {"auth": -1}},
    {"id": 26, "question": "The police were not created to protect the people, but to uphold the status quo by force.", "effects": {"auth": -1}},
    {"id": 27, "question": "Government owned schools are a bad idea because our government shouldn't be influencing our children.", "effects": {"auth": -1}},
    {"id": 28, "question": "The government should allow two consenting individuals to be able to do whatever they want with each other.", "effects": {"prog": 1}},
    {"id": 29, "question": "The government should allow an individual to be able to do anything they desire to their own body.", "effects": {"prog": 1}},
    {"id": 30, "question": "The government should allow freedom of religion.", "effects": {"prog": 1}},
    {"id": 31, "question": "The government should allow nudism in public.", "effects": {"prog": 1}},
    {"id": 32, "question": "The government should recognize certain animal rights.", "effects": {"prog": 1}},
    {"id": 33, "question": "Laws based on cultural values, rather than ethical ones, aren't justice.", "effects": {"prog": 1}},
    {"id": 34, "question": "Autonomy of body extends even to minors, the mentally ill, and serious criminals.", "effects": {"prog": 1}},
    {"id": 35, "question": "The government should not recognize gay marriage.", "effects": {"prog": -1}},
    {"id": 36, "question": "The government should not recognize gender transitions.", "effects": {"prog": -1}},
    {"id": 37, "question": "The government should ban drugs.", "effects": {"prog": -1}},
    {"id": 38, "question": "The death penalty should be enforced by the government as a form of punishment.", "effects": {"prog": -1}},
    
