questions =  [
    {"id": 0, "question": "The government should reduce business regulations.", "effects": {"right": 1, "auth": -1}},
    {"id": 1, "question": "The government should increase the minimum wage to help workers earn more to offset living costs.", "effects": {"right": -1, "auth": 1}},
    {"id": 2, "question": "The government should limit CEO pay so it does not exceed a certain ratio compared to average worker pay.", "effects": {"right": -1, "auth": 1}},
    {"id": 3, "question": "The government should put a cap on banker bonus pay.", "effects": {"right": -1, "auth": 1}},
    {"id": 4, "question": "The government should mandate businesses adopt a 4 day work week.", "effects": {"right": -1, "auth": 1}},
    {"id": 5, "question": "The ideal form of society is one without government, money, social classes, and private property.", "effects": {"right": -3}},
    {"id": 6, "question": "The government should tax the wealthy to reduce inequality.", "effects": {"right": -1, "auth": 1}},
    {"id": 7, "question": "The government should tax corporations based on the quantity of carbon emissions they produce.", "effects": {"right": -1, "auth": 1}},
    {"id": 8, "question": "A universal basic income administered by the government is a good idea.", "effects": {"right": -1, "auth": 1}},
    {"id": 9, "question": "The government should provide unemployed people with jobs.", "effects": {"right": -1, "auth": 1}},
    {"id": 10, "question": "The current welfare system  should be expanded by the government to further combat inequality.", "effects": {"right": -1}},
    {"id": 11, "question": "The government should nationalize or redistribute land.", "effects": {"right": -2, "auth": 1}},
    {"id": 12, "question": "Banks should be government owned.", "effects": {"right": -1, "auth": 1}},
    {"id": 13, "question": "Utilities, like water and electricity should be government owned.", "effects": {"right": -2, "auth": 1}},
    {"id": 14, "question": "Prisons should be government owned and not privately owned.", "effects": {"right": -2, "auth": 1}},
    {"id": 15, "question": "Pharmacies should be government owned to reduce drug costs.", "effects": {"right": -2, "auth": 1}},
    {"id": 16, "question": "Retail firms like Amazon should be government owned.", "effects": {"right": -2, "auth": 1}},
    {"id": 17, "question": "Manufacturing firms should be government owned.", "effects": {"right": -2, "auth": 1}},
    {"id": 18, "question": "The goverment should relinquish state ownership of roads and privatize them.", "effects": {"right": 2, "auth": -2}},
    {"id": 19, "question": "The goverment should relinquish state ownership of trains and privatize them.", "effects": {"right": 2, "auth": -2}},
    {"id": 20, "question": "The goverment should relinquish state ownership of airports and privatize them.", "effects": {"right": 2, "auth": -2}},
    {"id": 21, "question": "The government should encourage and/or mandate the conversion of currently existing stores or the formation of worker cooperative owned grocery stores.", "effects": {"right": -2, "auth": 0.5}},
    {"id": 22, "question": "There should be government owned housing leased to citizens for 99 years.", "effects": {"right": -2, "auth": 1}},
    {"id": 23, "question": "The government should have the ability to own the stocks of businesses.", "effects": {"right": -2, "auth": 1}},
    {"id": 24, "question": "The government should have a sovereign wealth fund that invests its money in private assets such as stocks, bonds, and equity.", "effects": {"right": -2, "auth": 1}},
    {"id": 25, "question": "The government should make sure the economy is fully government owned and managed by a group of central planners organizing everything from the top down.", "effects": {"right": -3, "auth": 3}},
    {"id": 26, "question": "A flat tax should fund government services.", "effects": {"right": 1}},
    {"id": 27, "question": "Progressive taxation should fund government services.", "effects": {"right": -1}},
    {"id": 28, "question": "The government should provide free preschool.", "effects": {"right": -1, "auth": 1}},
    {"id": 29, "question": "The government should provide free college.", "effects": {"right": -1, "auth": 1}},
    {"id": 30, "question": "The government should provide free healthcare.", "effects": {"right": -1, "auth": 1}},
    {"id": 31, "question": "The government should provide free dental care.", "effects": {"right": -1, "auth": 1}},
    {"id": 32, "question": "The government should provide free food.", "effects": {"right": -1, "auth": 1}},
    {"id": 33, "question": "The government should provide free milk deliveries to homes.", "effects": {"right": -1, "auth": 1}},
    {"id": 34, "question": "The government should provide free infant products for new parents.", "effects": {"right": -1, "auth": 1}},
    {"id": 35, "question": "The government should provide free gender affirming care.(Hormones, surgeries)", "effects": {"right": -1, "auth": 1, "prog": 1}},
    {"id": 36, "question": "The government should be required to spend within its budget and not overspend with deficit spending.", "effects": {"right": 1, "auth": -1}},
    {"id": 37, "question": "The government should allow citizens to vote on the budget and what to spend on.", "effects": {"right": -1, "auth": -1}},
    {"id": 38, "question": "The government should mandate business profits be shared with workers.", "effects": {"right": -1, "auth": 1}},
    {"id": 39, "question": "The government should mandate businesses give workers stock ownership.", "effects": {"right": -1.5, "auth": 1}},
    {"id": 40, "question": "The government should mandate businesses to allow workers to vote for other workers to be seated on its board of directors and represent them.", "effects": {"right": -1, "auth": 1}},
    {"id": 41, "question": "The government should mandate businesses to have women to be seated on its board of directors and represent them.", "effects": {"right": -1, "auth": 1, "prog": 1}},
    {"id": 42, "question": "The government should assist in the formation of worker cooperatives.", "effects": {"right": -2, "auth": 1}},
    {"id": 43, "question": "The government should mandate schools provide free lunches.", "effects": {"right": -1, "auth": 1}},
    {"id": 44, "question": "The government should abolish patent laws.", "effects": {"right": -1, "auth": -1}},
    {"id": 45, "question": "The government should reduce its regulations on banks.", "effects": {"right": -1, "auth": -1}},
    {"id": 46, "question": "Sometimes it is right that the government may spy on its citizens to combat extremists and terrorists.", "effects": {"auth": 1}},
    {"id": 47, "question": "Strength is necessary for any government to succeed.", "effects": {"auth": 1}},
    {"id": 48, "question": "Only the government can fairly and effectively regulate organisations.", "effects": {"auth": 1}},
    {"id": 49, "question": "Mandatory IDs should be used by the goverment to ensure public safety.", "effects": {"auth": 1}},
    {"id": 50, "question": "When a pandemic happens, the government should institute mask and vaccine mandates.", "effects": {"auth": 1}},
    {"id": 51, "question": "The government should be less involved in the day to day life of its citizens.", "effects": {"auth": -1}},
    {"id": 52, "question": "Monarchical governments are better than democratic governments.", "effects": {"auth": 1, "right": 1}},
    {"id": 53, "question": "A violent revolution should be enacted to overthrow an existing government to being about radical and progressive changes to society.", "effects": {"auth": 3,"right": -3}},
    {"id": 54, "question": "The government should be a one party vanguard, also known as dictatorship of the proletariat, with the goal of instituting socialism.", "effects": {"auth": 3, "right": -3}},
    {"id": 55, "question": "Criminals should be given the right to a fair trial by the government.", "effects": {"auth": -1}},
    {"id": 56, "question": "The government should provide emergency services and law enforcement.", "effects": {"auth": 1}},
    {"id": 57, "question": "The government should get rid of police.", "effects": {"auth": -3}},
    {"id": 58, "question": "The government should get rid of the military.", "effects": {"auth": -3}},
    {"id": 59, "question": "Government owned schools are a bad idea because our government shouldn't be influencing our children.", "effects": {"auth": -1, "right": 1}},
    {"id": 60, "question": "The government should allow two consenting individuals to be able to do whatever sexual act they desire with each other in the privacy of their own bedroom.", "effects": {"prog": 1, "auth": -1}},
    {"id": 61, "question": "The government should allow an individual to be able to do anything they desire to their own body.", "effects": {"prog": 1, "auth": -1}},
    {"id": 62, "question": "The government should ban parents from hitting their children.", "effects": {"prog": 1, "auth": 1}},
    {"id": 63, "question": "The government should allow freedom of religion.", "effects": {"prog": 1, "auth": -3}},
    {"id": 64, "question": "The government should allow nudism in public.", "effects": {"prog": 3, "auth": -3}},
    {"id": 65, "question": "The government should recognize certain animal rights.", "effects": {"prog": 1, "auth": -1}},
    {"id": 66, "question": "Abortion should be restricted or banned by the government.", "effects": {"prog": -3, "auth": 3}},
    {"id": 67, "question": "Individuals who undergo abortions should be executed by the government.", "effects": {"prog": -3, "auth": 3}},
    {"id": 68, "question": "Physicians who perform abortions should be executed by the government.", "effects": {"prog": -3, "auth": 3}},
    {"id": 69, "question": "Abortion should be made mandatory by the government for deformed, disabled, or racially undesirable fetuses.", "effects": {"prog": -3, "auth": 3}},
    {"id": 70, "question": "The government should allow children to do whatever with their bodies, such as undergoing puberty blockers, hormone treatments, tattoos, piercings, or plastic surgery.", "effects": {"prog": 1}},
    {"id": 71, "question": "The government should ban gay marriage.", "effects": {"prog": -3, "auth": 3}},
    {"id": 72, "question": "The government should not be involved in any and all marriages regardless if they are gay or straight ones.", "effects": {"auth": -1}},
    {"id": 73, "question": "The government should not allow the changing of someone's legal gender to a different one on their birth certificate.", "effects": {"prog": -3, "auth": 3}},
    {"id": 74, "question": "The government should ban or restrict drugs.", "effects": {"prog": -1, "auth": 1, "right": -1}},
    {"id": 75, "question": "The government should ban prostitution.", "effects": {"prog": -1, "auth": 1, "right": -1}},
    {"id": 76, "question": "The government should ban pornography.", "effects": {"prog": -1, "auth": 1, "right": -1}},
    {"id": 77, "question": "The government should ban gambling.", "effects": {"prog": -1, "auth": 1, "right": -1}},
    {"id": 78, "question": "The government should ban or restrict guns.", "effects": {"auth": 1}},
    {"id": 79, "question": "The government should ban or restrict knives.", "effects": {"auth": 2}},
    {"id": 80, "question": "The government should ban or restrict immigration.", "effects": {"auth": 3, "prog": -3}},
    {"id": 81, "question": "The government should remove children not born in the country and send them back to their birth country.", "effects": {"auth": 3, "prog": -3}},
    {"id": 82, "question": "The government should prosecute hate speech against minorities.", "effects": {"auth": 2, "prog": 2, "right": -2}},
    {"id": 83, "question": "The government should punish whistleblowers who leak confidential government information.", "effects": {"auth": 1}},
    {"id": 84, "question": "The government should enforce a system of racial hierarchy such as segregation, apartheid, or slavery.", "effects": {"prog": -3, "auth": 3, "right": 3}},
    {"id": 85, "question": "The government should exterminate racial, religious, and/or social minorities.", "effects": {"prog": -3, "auth": 3}},
    {"id": 86, "question": "The government should enforce a system of political, social, and economic hierarchy where the lowest class is owned and dependent on a higher class and required to work for them, with the ruling class being a monarch who heads the system.", "effects": {"auth": 1, "right": 1}},
    {"id": 87, "question": "The death penalty should be enforced by the government as a form of punishment.", "effects": {"auth": 2}},
    {"id": 88, "question": "The goverment should reform prisons to allow weekday only imprisonment.", "effects": {"auth": -3}},
    {"id": 89, "question": "The goverment should allow prisoners to leave prison temporarily for a few hours a day to pursue education and/or work.", "effects": {"auth": -3}},
    {"id": 90, "question": "The goverment should allow prisoners ownership of their own cell keys.", "effects": {"auth": -3}},
    {"id": 91, "question": "The government should be a theocracy(system of government led by leaders of a religion).", "effects": {"auth": 3, "right": 3, "prog": -3}},
    {"id": 92, "question": "Labour or concentration camps should be enforced by the government as a form of punishment.", "effects": {"auth": 3}},
    {"id": 93, "question": "The government should have an informant system so that any anti government activities are punished.", "effects": {"auth": 3}},
    {"id": 94, "question": "The government should recognize the right to protest.", "effects": {"auth": -1}},
    {"id": 95, "question": "The government should violently shut down a peaceful protest with force.", "effects": {"auth": 1}},
    {"id": 96, "question": "The government should ban books discussing the civil rights movement and its leaders as well as books discussing the history of African slavery from schools.", "effects": {"auth": 3, "prog": -3, "right": 3}},
    {"id": 97, "question": "The government should ban evolution being taught in schools.", "effects": {"auth": 3, "prog": -3}},
    {"id": 98, "question": "The government should pass a resolution recognizing only 2 genders.", "effects": {"auth": 3, "prog": -3}},
    {"id": 99, "question": "The government should ban books discussing sexuality and gender identity from schools.", "effects": {"auth": 3, "prog": -3}},
    {"id": 100, "question": "The government should allow women the right to vote.", "effects": {"auth": -3}},
    {"id": 101, "question": "The government should allow citizens the right to vote in yearly referendums on policies.", "effects": {"auth": -1}},
    {"id": 102, "question": "The government should allow citizens to vote using the Internet.", "effects": {"auth": -2}},
    {"id": 103, "question": "The government should allow citizens to vote through ballots sent via mail.", "effects": {"auth": -1}},
    {"id": 104, "question": "The government should have multiple heads of state rather than a singular head of state/president/prime minister.", "effects": {"auth": -5}},
    {"id": 105, "question": "The government should set term limits on members of the legislature.", "effects": {"auth": -1}},        
    {"id": 106, "question": "The government should ban legislative members from owning stocks.", "effects": {"auth": -1}},    
    {"id": 107, "question": "The government should ban citizens from having in public flags like the Confederate flag and Nazi flag due to their offensive racial ties.", "effects": {"auth": 2, "prog": 2, "right": -2}}, 
    {"id": 108, "question": "The government should ban businesses from excluding services from people based on race, gender, and sexuality.", "effects": {"auth": 2, "prog": 2, "right": -2}}, 
    {"id": 109, "question": "The government should ban colleges from using affirmative action in admissions.", "effects": {"auth": 2, "prog": -2, "right": 2}},
    {"id": 110, "question": "The government should ban surgery on intersex infants.", "effects": {"auth": 2, "prog": 2, "right": -2}},
    {"id": 111, "question": "The government should ban businesses from firing employees based on religion, race, gender, or sexuality.", "effects": {"auth": 2, "prog": 2, "right": -2}},
    {"id": 112, "question": "The government should punish educational institutions for promoting LGBT views on sexuality and gender.", "effects": {"auth": 3, "prog": -3, "right": 3}},
    {"id": 113, "question": "The government should suspend all laws and the constitution in response to a perceived threat to protect the country.", "effects": {"auth": 5}},
    {"id": 114, "question": "The government should suspend build a border wall to restrict illegal immigration into the country.", "effects": {"auth": 5, "prog": -5, "right": 5}},
    {"id": 115, "question": "The government should ban pride marches.", "effects": {"auth": 3, "prog": -3, "right": 3}}
];
