questions =  [
    {"id": 0, "question": "The government should reduce business regulations.", "effects": {"right": 1}},
    {"id": 1, "question": "The government should increase the minimum wage to help workers earn more to offset living costs.", "effects": {"right": -1}},
    {"id": 2, "question": "The ideal form of society is one without government, money, social classes, and private property.", "effects": {"right": -1}},
    {"id": 3, "question": "The government should tax the wealthy to reduce inequality.", "effects": {"right": -1}},
    {"id": 4, "question": "A universal basic income administered by the government is a good idea.", "effects": {"right": -1}},
    {"id": 5, "question": "The current welfare system  should be expanded by the government to further combat inequality.", "effects": {"right": -1}},
    {"id": 6, "question": "The government should nationalize or redistribute land.", "effects": {"right": -1}},
    {"id": 7, "question": "Banks should be government owned.", "effects": {"right": -1}},
    {"id": 8, "question": "The government should provide free preschool.", "effects": {"right": -1}},
    {"id": 9, "question": "The government should provide free college.", "effects": {"right": -1, "auth": 1}},
    {"id": 10, "question": "The government should provide free healthcare.", "effects": {"right": -1}},
    {"id": 11, "question": "The government should mandate business profits be shared with workers.", "effects": {"right": -1}},
    {"id": 12, "question": "The government should mandate businesses give workers stock ownership.", "effects": {"right": -1}},
    {"id": 13, "question": "The government should mandate schools provide free lunches.", "effects": {"right": -1}},
    {"id": 14, "question": "Sometimes it is right that the government may spy on its citizens to combat extremists and terrorists.", "effects": {"auth": 1}},
    {"id": 15, "question": "Authority figures, if morally correct, are a good thing for society.", "effects": {"auth": 1}},
    {"id": 16, "question": "Strength is necessary for any government to succeed.", "effects": {"auth": 1}},
    {"id": 17, "question": "Only the government can fairly and effectively regulate organisations.", "effects": {"auth": 1}},
    {"id": 18, "question": "Society requires structure and bureaucracy in order to function.", "effects": {"auth": 1}},
    {"id": 19, "question": "Mandatory IDs should be used by the goverment to ensure public safety.", "effects": {"auth": 1}},
    {"id": 20, "question": "In times of crisis, safety becomes more important than civil liberties.", "effects": {"auth": 1}},
    {"id": 21, "question": "The government should be less involved in the day to day life of its citizens.", "effects": {"auth": -1}},
    {"id": 22, "question": "Monarchical governments are better than democratic governments.", "effects": {"auth": 1, "right": 1}},
    {"id": 23, "question": "Jury nullification should be legal.", "effects": {"auth": -1}},
    {"id": 24, "question": "The smaller the government, the freer the people.", "effects": {"auth": -1}},
    {"id": 25, "question": "The government should, at most, provide emergency services and law enforcement.", "effects": {"auth": -1}},
    {"id": 26, "question": "The police were not created to protect the people, but to uphold the status quo by force.", "effects": {"auth": -1}},
    {"id": 27, "question": "Government owned schools are a bad idea because our government shouldn't be influencing our children.", "effects": {"auth": -1}},
    {"id": 28, "question": "The government should allow two consenting individuals to be able to do whatever they want with each other.", "effects": {"prog": 1}},
    {"id": 29, "question": "The government should allow an individual to be able to do anything they desire to their own body.", "effects": {"prog": 1}},
    {"id": 30, "question": "The government should allow freedom of religion.", "effects": {"prog": 1}},
    {"id": 31, "question": "The government should allow nudism in public.", "effects": {"prog": 1}},
    {"id": 32, "question": "The government should recognize certain animal rights.", "effects": {"prog": 1}},
    {"id": 33, "question": "Laws based on cultural values, rather than ethical ones, aren't justice.", "effects": {"prog": 1}},
    {"id": 34, "question": "The government should allow children to do whatever with their bodies, such as undergoing puberty blockers, hormone treatments, tattoos, piercings, or plastic surgery.", "effects": {"prog": 1}},
    {"id": 35, "question": "The government should not recognize gay marriage.", "effects": {"prog": -1, "auth": 1}},
    {"id": 36, "question": "The government should not recognize gender transitions.", "effects": {"prog": -1, "auth": 1}},
    {"id": 37, "question": "The government should ban drugs.", "effects": {"prog": -1, "auth": 1}},
    {"id": 38, "question": "The death penalty should be enforced by the government as a form of punishment.", "effects": {"auth": 1}}
];
